api/urls.py
from django.urls import path, include
from api.models import TourResource, CategoryResource
from tastypie.api import Api

api = Api(api_name='v1')
tour_resource = TourResource()
category_resource = CategoryResource()
api.register(tour_resource)
api.register(category_resource)


# api/v1/tours/         GET, POST
# api/v1/tours/1/       GET, DELETE
# api/v1/categories/    GET
# api/v1/categories/1/


urlpatterns = [
    path('', include(api.urls), name='index')
]

base/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    # path('api/', include(tour_resource.urls)),
    # path('api/', include(category_resource.urls)),


]

shop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),  # путь к главной странице
    path('<int:tour_id>', views.single_tour, name='single_tour'),
    path('<int:tour_id>/create', views.createreview, name='createreview'),
    path('review/<int:review_id>', views.updatereview, name='updatereview'),
    path('review/<int:review_id>/delete',
         views.deletereview, name='deletereview'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        # чтобы видно было в админ панели на web название кат
        return self.title


class Tour(models.Model):
    title = models.CharField(max_length=300)
    description = models.CharField(max_length=900)
    price = models.IntegerField()
    place_qty = models.IntegerField()
    image = models.ImageField(upload_to='shop/images/')
    meeting_time = models.CharField(max_length=5)
    meeting_place = models.CharField(max_length=100)
    duration = models.FloatField(blank=True)
    # free_places = models.IntegerField()
    # reserved_places = models.IntegerField()
    # pri odstraneni Categorie, automatickz se odstrani vsechny kurzy v teto Cat
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title
        # return self.title + ' '+str(self.students_qty)


class Review(models.Model):
    text = models.CharField(max_length=300)
    # the current datetime will be automatically filled in. This makes the field non-editable. Once the datetime is set, it is fixed
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)
    stars = models.IntegerField()
    recommend = models.BooleanField()

    def __str__(self):
        return self.text

shop/forms.py
from django.forms import ModelForm, Textarea, IntegerField
from .models import Review


class ReviewForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        # set for each form field a class attribute to use a Bootstrap class.
        self.fields['text'].widget.attrs.update({'class': 'form-control'})
        # set for each form field a class attribute to use a Bootstrap class.
        self.fields['stars'].widget.attrs.update({'class': 'form-control'})
        self.fields['recommend'].widget.attrs.update(
            {'class': 'form-check-input'})

    class Meta:
        """
        A class inside a class! 
        Specify which model the form is for and the fields we want in the form.

        More in documentation: 
        https://docs.djangoproject.com/en/4.2/topics/forms/modelforms/
        """
        model = Review
        # the only fields that the user has to fill are these
        fields = ['text', 'stars', 'recommend']
        labels = {
            'recommend': ('Recommend'),
            'stars': ('Stars')
        }
        widgets = {
            'text': Textarea(attrs={'rows': 4}),
            # 'stars': IntegerField(attrs={'rows': 1}),

        }

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import Tour, Review
from .forms import ReviewForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    searchTerm = request.GET.get('searchTour')
    if searchTerm:
        tours = Tour.objects.filter(title__icontains=searchTerm)
    else:
        tours = Tour.objects.all()
    return render(request=request, template_name='shop/tours.html', context={'searchTerm': searchTerm, 'tours': tours})


# def index(request):
#     tours = Tour.objects.all()
#     return render(request=request, template_name='shop/tours.html', context={'tours': tours})
    # return HttpResponse("Hello")

@login_required  # <- a decorator to make sure that the view is only accessible to the logged in users
def createreview(request, tour_id):
    tour = get_object_or_404(Tour, pk=tour_id)
    if request.method == 'GET':
        return render(request, 'shop/createreview.html', {'form': ReviewForm(), 'tour': tour})
    else:
        try:
            form = ReviewForm(request.POST)
            # We create and save a new review object from the form's values but do not yet put it into the database (commit=False) because we want to specify the user and movie relationships for the review.
            newReview = form.save(commit=False)
            newReview.user = request.user
            newReview.tour = tour
            newReview.save()
            return redirect('shop:single_tour', newReview.tour.id)
        except ValueError:
            return render(request, 'shop/createreview.html', {'form': ReviewForm(), 'error': 'bad data passed in'})


def single_tour(request, tour_id):
    # Option 1
    # try:
    #     tour = Tour.objects.get(pk=tour_id)
    #     return render(request, 'shop/single_tour.html', {'tour': tour})
    # except Tour.DoesNotExist:
    #     raise Http404()

    # Option 2
    tour = get_object_or_404(Tour, pk=tour_id)
    persons_number = request.GET.get('calculate')
    total_price = 0
    if persons_number is not None:
        total_price = int(persons_number)*tour.price
        # print("Total price, ", total_price)
    reviews = Review.objects.filter(tour=tour)

    return render(request, 'shop/single_tour.html', {'tour': tour, 'total_price': total_price, 'reviews': reviews})


@login_required
def updatereview(request, review_id):
    # supply the logged-in user to ensure that other users can't access the review – for example, if they manually enter the URL path in the browser. Only the user who created this review can update/delete it.
    review = get_object_or_404(Review, pk=review_id, user=request.user)
    if request.method == 'GET':
        form = ReviewForm(instance=review)
        # render ReviewForm we used previously in creating a review, but this time, we pass the review object into the form so that the form's fields will be populated with the object's values, ready for the user to edit. Saves us time!
        return render(request, 'shop/updatereview.html', {'review': review, 'form': form})
    else:
        try:
            form = ReviewForm(request.POST, instance=review)
            form.save()
            return redirect('shop:single_tour', review.tour.id)
        except ValueError:
            return render(request, 'updatereview.html', {'review': review, 'form': form, 'error': 'Bad data in form'})


@login_required
def deletereview(request, review_id):
    review = get_object_or_404(Review, pk=review_id, user=request.user)
    review.delete()
    return redirect('shop:single_tour', review.tour.id)

templates/shop/createreview.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{tour.title}}{% endblock %}
{% block content %}
<div class="container">
    <div class="card my-5">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h5 class="card-title">Add Review for <span class="text-success">{{ tour.title }}</span></h5>
                    {% if error %}
                    <div class="alert alert-danger mt-3" role="alert">
                        {{ error }}
                    </div>
                    {% endif %}
                    <p class="card-text">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btnwhite border border-danger border-1 rounded-pill px-4 py-1 text-danger">
                            Add Review
                        </button>
                    </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/shop/single_tour.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{tour.title}}{% endblock %}

{% block content %}
<div class="container mb-5">
    <h1 class="mt-5 mb-5">{{tour.title}}</h1>
    <div class="row">
        <div class="col-sm-8">
            <p>{{ tour.description }}</p>
        </div>
        <div class="col-sm-4 bg-danger text-center bg-danger bg-opacity-10 border border-3 border-danger rounded">
            <p class="pt-5"><b>Price:</b> {{tour.price}} euro</p>
        </div>
    </div>
    
    <p><b>Group`s quantity:</b> {{tour.place_qty}} people</p>
    <p><b>Meeting place:</b> {{tour.meeting_place}}</p>
    <p><b>Meeting time:</b> {{tour.meeting_time}}</p>
    <p><b>Duration:</b> {{tour.duration}} hours</p>


    <h3>Calculate price</h3>
    <form action="" class="bg-dark p-5 price mb-5">
        <label class="text-danger pe-5">Choose number of people</label>
        <input name="calculate" type="number" class="border border-1 border-danger bg-danger bg-opacity-10 text-danger">
        <button class="btn btnwhite border border-danger border-1 rounded-pill px-4 py-1 text-danger ms-5">Calculate price</button>
    </form>
    <h5 class="mb-3">Total price: <b>{{ total_price }}</b> EUR</h5>
    <button class="btn btnwhite border border-danger border-1 rounded-pill px-4 py-1 text-danger">Buy</button>


    <h3 class="mt-5">Reviews</h3>
    <!-- new code -->
    {% if user.is_authenticated %}
    <!-- Users who are not logged in will not see the Add Review link. -->
        <a href="{% url 'shop:createreview' tour.id %}" class="btn btnwhite border border-danger border-1 rounded-pill px-4 py-1 text-danger my-3">Add Review</a>
    {% endif %}

    {% if user.is_authenticated and not reviews%}
        <h5>There is no any review jet.  Leave your feedback and be the first.</h5>
    {% elif not reviews %}
        <h5>There is no any review yet.</h5>
    {% endif %}

    
    <ul class="list-group">
        {% for review in reviews %}
        <li class="list-group-item pb-3 pt-3">
            <h5 class="card-title">
                Review by <span class="text-success">{{ review.user.username }}</span>
            </h5>
            <h6 class="card-subtitle mb-2 text-muted">
                {{ review.date }}
            </h6>
            <p class="card-text">{{ review.text }}</p>
            <p class="card-text">I give: {{ review.stars }} stars</p>

            {% with ''|center:review.stars as stars %}
            {% for _ in stars %}
                <img src="../../media/shop/images/star.png" alt="Star">
            {% endfor %}                
            {% endwith %}

            <br>
            

            {% if user.is_authenticated and user == review.user %}
                <a class="btn btnwhite border border-danger border-1 rounded-pill px-4 py-1 text-danger me-2 mt-3" href="{% url 'shop:updatereview' review.id %}">Update</a>
                <a class="btn btn-danger rounded-pill px-4 py-1 mt-3" href="{% url 'shop:deletereview' review.id %}">Delete</a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>

</div>

<section id="last_photo" class="img-fluid  pt-4 pb-5 d-flex justify-content-center  align-items-center">
    <div id="overlay"></div>
    <div class="container d-flex justify-content-center text-center  text-black">
        <div class=" above container_sm mt-4">
            <p class="pb-3 fs-5 lh-lg text-white">Welcome to the Czech Republic, a captivating country nestled in the heart of Europe. From its enchanting medieval castles and cobblestone streets to its lush green landscapes and rich cultural heritage, the Czech Republic offers a truly unforgettable experience.</p>
            <p class="pb-5 fs-5 lh-lg text-white">Delight in the world-famous Pilsner beer, explore the charming alleys of Prague's Old Town, and immerse yourself in the nation's love for art, music, and literature.</p>
            <p class=" pb-5 fs-5 fw-bold text-white">Create memories for a lifetime.</p>
        </div>
    </div>
</section>


{% endblock %}


        {% comment %} <div class="p-5 col-sm-4 bg-info bg-opacity-10 border border-3 border-info rounded"> {% endcomment %}

templates/shop/tours.html
{% extends 'base.html' %}

{% block title %}Mary`s main page{% endblock %}

{% block content %}
<section id="kardy">
    <div class="container pt-5 pb-3 text-center">
        <h2 class="fw-bold">Greetings!</h2>
        <h4 class="fw-bold">Embark on a captivating journey through the my website. Discover remarkable tours, hidden gems and travel tips that will make your adventures unforgettable.</h4>
        <h4 class="fw-bold">Enjoy exploring!</h4>
    </div>
    <div class="container pt-5 pb-3 text-center">
        <h1 class="fw-bold">My tours</h1>
    </div>
    {% comment %} S E A R C H {% endcomment %}
    <div class="container pt-5 pb-3">
        <form action="">
            <div class="mb-3 linie">
                <input type="text" name="searchTour" class="form-control bg-danger bg-opacity-10 border border-1 border-danger">
            </div>
            <button type="submit" class="btn btnwhite border border-danger border-1 rounded-pill px-4 py-1 my-3 text-danger">
                Search
            </button>
        </form>
    </div>

    {% comment %} CARDS (tours) from DB {% endcomment %}
    <div class="container d-flex justify-content-between gy-2 pb-5">
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4">
            {% for tour in tours %}
            <div v-for="tour in tours" class="col mb-2">
                <div class="blog card h-100 bg-light border rounded">
                    <img class="card-img-top" src="{{ tour.image.url }}" alt="photo">
                    <div class="card-body" style="height: 18rem; overflow: hidden;">
                        <h5 class="card-title fw-bold ms-2"><a class="text-danger" href="{{tour.id}}">{{ tour.title }}</a></h5>
                        <p class="card-text ms-2">{{ tour.description }}</p>
                    </div>
                    <div class="card-footer mb-3 border-0 bg-light">
                        <a class="btnwhite border border-danger border-2 rounded-pill px-4 text-danger ms-2"
                        href="{% url 'shop:single_tour' tour.id %}">Read more ...</a>
                        {% comment %}  2. вариант, если в urls.py (shop) убрать app_name = 'shop', то и здесь удалить shop: 1.- см. h5 card-title,{% endcomment %}
                    </div>
                </div>
            </div>        
            {% endfor %}
        </div>
    </div>
   
</section>
{% endblock %}

templates/shop/updatereview.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{tour.title}}{% endblock %}
{% block content %}
<div class="container mb-5">
    <div class="card my-5">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h5 class="card-title">
                        Update Review for <span class="text-success"> {{ review.tour.title }}</span>
                    </h5>
                    {% if error %}
                    <div class="alert alert-danger mt-3" role="alert">
                        {{ error }}
                    </div>
                    {% endif %}
                    <p class="card-text">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btnwhite border border-danger border-1 rounded-pill px-4 py-1 text-danger me-2">
                            Update Review
                        </button>
                    </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}